spring:
  application:
    name: TAEG-Sevice
  datasource:
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_cluster_lambda
    username: freedb_lambda
    password: xn!UFZ?#Q39HnWp
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
